[package]
name = "teahub"
version = "0.1.0"
edition = "2021"

[dependencies]
http_req = { version = "0.10.0", default-features = false, features = [
    "rust-tls",
] }
serde = "1.0.189"
serde_derive = "1.0.189"
serde_json = "1.0.107"
toml = "0.8.2"
